- name: install deps
  dnf: name={{ item }} state=present
  with_items:
    - libtiff-devel
    - libjpeg-devel
    - libzip-devel
    - freetype-devel
    - lcms2-devel
    - libwebp-devel
    - tcl-devel
    - tk-devel
    - python-virtualenv
    - libffi-devel
    - openssl-devel
