#cloud-config

coreos:
  etcd:
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001

  fleet:
    metadata: kind=solo

  units:
    - name: etcd.service
      command: start

    - name: fleet.service
      command: start

    - name: docker-tcp.socket
      command: start
      content: |
        [Unit]
        Description=Docker Socket for Remote API

        [Socket]
        ListenStream=4243
        Service=docker.service
        BindIPv6Only=both

        [Install]
        WantedBy=sockets.target

    - name: stop-update-engine.service
      command: start
      content: |
        [Unit]
        Description=stop update-engine

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/systemctl stop update-engine.service
        ExecStartPost=/usr/bin/systemctl mask update-engine.service

    - name: dotfiles.service
      command: start
      content: |
        [Unit]
        Description=Pull my dotfiles
        Requires=docker.service

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/docker pull xena/dotfiles
        RemainAfterExit=true

    - name: ntpdate.service
      command: start

    - name: timedate-ntp-synchronization.service
      command: start
      content: |
        [Unit]
        Description=Synchronize system clock
        After=ntpdate.service

        [Service]
        ExecStart=/usr/bin/timedatectl set-timezone UTC
        ExecStart=/usr/bin/timedatectl set-ntp true
        ExecStart=/sbin/hwclock --systohc --utc
        RemainAfterExit=yes
        Type=oneshot

  update:
    reboot-strategy: off
    group: "alpha"

write_files:
  - path: /etc/systemd/system/fleet.socket.d/30-ListenStream.conf
    content: |
      [Socket]
      ListenStream=127.0.0.1:49153

hostname: solo

users:
  - name: xena
    gecos: Christine Dodrill
    groups:
     - sudo
     - docker
    coreos-ssh-import-github: Xe
