#cloud-config

---
coreos:
  etcd:
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001
    discovery: replace-me

  fleet:
    public-ip: $public_ipv4

  flannel:
    interface: $public_ipv4

  units:
    - name: etcd.service
      command: start

    - name: fleet.service
      command: start

    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=2375
        Service=docker.service
        BindIPv6Only=both

        [Install]
        WantedBy=sockets.target

    - name: pull-dotfiles.service
      command: start
      content: |
        [Unit]
        Description=Pull my dotfiles
        Requires=docker.service
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/docker pull xena/dotfiles
        ExecStart=/usr/bin/docker run -dit -v /home/xena/var:/home/xena/var -v /home/xena/var/bin:/home/xena/bin -v /dev/log:/dev/log -v /dev/fuse:/dev/fuse --net=host --privileged --restart=always --name shell xena/dotfiles
        RemainAfterExit=true

    - name: ntpdate.service
      command: start

    - name: timedate-ntp-synchronization.service
      command: start
      content: |
        [Unit]
        Description=Synchronize system clock
        After=ntpdate.service
        [Service]
        ExecStart=/usr/bin/timedatectl set-timezone UTC
        ExecStart=/usr/bin/timedatectl set-ntp true
        ExecStart=/sbin/hwclock --systohc --utc
        RemainAfterExit=yes
        Type=oneshot

users:
  - name: xena
    gecos: Christine Dodrill
    groups:
     - sudo
     - docker
     - portage
     - wheel
     - systemd-journal
    coreos-ssh-import-github: Xe
