---
# Docker

- name: docker group
  group:
    name: docker
    state: present

- name: set up docker config
  copy:
    src: docker-storage
    dest: /etc/sysconfig/docker-storage
  notify:
    - restart docker
