---
- name: create xena user account
  user:
    name: xena
    comment: Christine Dodrill
    groups: docker,tty
    shell: /bin/zsh
    state: present

- name: download xena ssh keys from github
  become: yes
  become_user: xena
  authorized_key:
    user: xena
    key: https://github.com/Xe.keys
