- name: clone dotfiles
  git:
    repo: git@github.com:Xe/dotfiles
    dest: ~/code/dotfiles
  ignore_errors: yes

- name: install dotfiles
  script: ./scripts/devtools/setup_dotfiles.sh creates=/home/xena/code/dotfiles/.zshrc
