- name: delete awaynick.so
  file:
    path: /home/znc/prefix/lib/znc/awaynick.so
    state: absent

- name: create folders
  become: yes
  become_user: znc
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/znc/.znc
    - /home/znc/.znc/modules

- name: copy modules
  become: yes
  become_user: znc
  copy:
    src: "{{ item }}"
    dest: "/home/znc/.znc/modules/{{ item }}"
  with_items:
    - privmsg.cpp
    - ignore.cpp
    - antiperform.cpp

- name: build modules
  become: yes
  become_user: znc
  shell: "/home/znc/prefix/bin/znc-buildmod {{ item }}.cpp"
  args:
    creates: "{{ item }}.so"
    chdir: /home/znc/.znc/modules
  with_items:
    - privmsg
    - ignore
    - antiperform
