- name: delete awaynick.so
  file:
    path: /home/znc/prefix/lib/znc/awaynick.so
    state: absent

- name: add privmsg.cpp
  become: yes
  become_user: znc
  copy:
    src: privmsg.cpp
    dest: /home/znc/.znc/modules/privmsg.cpp

- name: build privmsg.cpp -> privmsg.so
  become: yes
  become_user: znc
  shell: /home/znc/prefix/bin/znc-buildmod privmsg.cpp
  args:
    creates: privmsg.so
    chdir: /home/znc/.znc/modules

- name: add ignore.cpp
  become: yes
  become_user: znc
  copy:
    src: ignore.cpp
    dest: /home/znc/.znc/modules/ignore.cpp

- name: build ignore.cpp -> ignore.so
  become: yes
  become_user: znc
  shell: /home/znc/prefix/bin/znc-buildmod ignore.cpp
  args:
    creates: ignore.so
    chdir: /home/znc/.znc/modules

- name: add antiperform.cpp
  become: yes
  become_user: znc
  copy:
    src: antiperform.cpp
    dest: /home/znc/.znc/modules/antiperform.cpp

- name: build antiperform.cpp -> privmsg.so
  become: yes
  become_user: znc
  shell: /home/znc/prefix/bin/znc-buildmod antiperform.cpp
  args:
    creates: antiperform.so
    chdir: /home/znc/.znc/modules
