#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    #discovery: https://discovery.etcd.io/c7a58e4df4623e4f9166e88ada333e11
    # multi-region and multi-cloud deployments need to use $public_ipv4
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  fleet:
    metadata: compute
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: docker-tcp.socket
      command: start
      content: |
        [Unit]
        Description=Docker Socket for Remote API

        [Socket]
        ListenStream=4243
        Service=docker.service
        BindIPv6Only=both

        [Install]
        WantedBy=sockets.target
    - name: sshd.socket
      command: restart
      content: |
        [Socket]
        ListenStream=2222
        Accept=yes
    - name: add-nse-alias.service
      command: start
      content: |
        [Unit]
        Description=Make an alias in the system

        [Service]
        Type=oneshot
        ExecStart=/bin/bash -c 'echo function nse() { sudo nsenter --pid --uts --mount --ipc --net --target $(docker inspect --format="{{ .State.Pid }}" $1) } >> /etc/profile.d/nse-alias.sh'

write_files:
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
      # Use most defaults for sshd configuration.
      UsePrivilegeSeparation sandbox
      Subsystem sftp internal-sftp

      PermitRootLogin no
      PasswordAuthentication no
      ChallengeResponseAuthentication no

update:
  reboot-strategy: off
  group: "alpha"

users:
  - name: xena
    gecos: Xena Cadenza
    groups:
     - sudo
     - docker
    coreos-ssh-import-github: Xe
